config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs do
    post 'toggle_confirmed', on: :member
  end

  resources :users do
  post 'toggle_isfrozen', on: :member
  end

  resources :beers

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resource :session, only: [:new, :create, :destroy]

  root 'breweries#index'

  get 'kaikki_bisset', to: 'beers#index'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  get 'beerlist', to:'beers#list'

  get 'brewerylist', to:'breweries#list'

  get 'ngbeerlist', to:'beers#nglist'

  get 'auth/:provider/callback', to: 'sessions#create_oauth'

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

  resources :ratings, only: [:index, :new, :create, :destroy]

end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
  has_many :memberships
  has_many :users, through: :memberships, source: :user


  def to_s
    name
  end

  def isMember(user)
    u = self.memberships.find_by(user_id: user.id , beer_club_id: self.id)
    if u.nil?
      return false
    elsif !u.confirmed
      return false
    else
      return true
    end
  end

  def hasApplied(user)
    u = self.memberships.find_by(user_id: user.id, beer_club_id: self.id)
    if !u.nil? and !u.confirmed
      return true
    else
      return false
    end
  end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @membership = Membership.new
    @membership.beer_club = @beer_club
    if @beer_club.memberships.each do |memberships|
      if not current_user.nil?
      if memberships.user.id == current_user.id
        @membership = memberships
      end
      end
    end
    end
  end

  def toggle_confirmed
    membership = Membership.find_by(user_id: params[:user_id], beer_club_id: params[:beer_club_id])
    membership.update_attribute :confirmed, true
    redirect_to :back, notice:"Membership accepted!"
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
        membership = Membership.new
        membership.user_id = current_user.id
        membership.beer_club_id = @beer_club.id
        membership.confirmed = true
        membership.save
      else
        format.html { render :new }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_club
      @beer_club = BeerClub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_club_params
      params.require(:beer_club).permit(:name, :founded, :city)
    end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_for(@beer_club) do |f| %>
  <% if @beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% @beer_club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :founded %><br>
    <%= f.number_field :founded %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-success"%>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing Beer Club</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer_club %> |
<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/index.html.erb
<h1>Listing Beer Clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Founded</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%=link_to beer_club.name, beer_club %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to('New Beer club', new_beer_club_path, class:'btn btn-success') if current_user %>

app/views/beer_clubs/new.html.erb
<h1>New Beer Club</h1>

<%= render 'form' %>

<%= link_to 'Back', beer_clubs_path, class:"btn btn-default" %>

app/views/beer_clubs/show.html.erb
<h2>
  <%= @beer_club.name %> <%= @beer_club.city %>
</h2>

<p>
  Founded
  <%= @beer_club.founded %>
</p>

<h3>Members</h3>
<ul>
  <% @beer_club.users.each do |user| %>
      <%if @beer_club.isMember(user) %>
    <li><%= link_to user.username, user_path(user)%></li>
      <% end %>
  <% end %>
</ul>

<% if current_user %>
<% if @beer_club.isMember(current_user) %>

    <h3>Outstanding applications</h3>
        <ul>
      <% @beer_club.memberships.each do |membership|  %>
          <% user1 = @beer_club.users.find_by id: membership.user_id %>
          <%if !@beer_club.isMember(user1) %>
                <li><%=user1.username%><%=" "%><%= link_to 'Confirm' , toggle_confirmed_beer_club_path(:user_id => membership.user_id,:beer_club_id => membership.beer_club_id), method: :post, class:'btn btn-primary' %> </li>
          <% end %>
      <% end %>
          </ul>
<% end %>
<% end %>

<% if current_user %>
    <% if not current_user.in? @beer_club.users %>
    <%= form_for(@membership) do |f| %>
        <%= f.hidden_field :beer_club_id %>
        <%= f.hidden_field :confirmed, :value => false %>
        <%= f.submit value:"join the club", class:"btn btn-success" %>
    <% end %>
        <br>
    <% end %>
    <% @beer_club.users.each do |user| %>
        <% if user.id == current_user.id %>
        <%= form_for(@membership, method: "delete") do |f| %>
            <%= f.hidden_field :beer_club_id %>
            <%= f.submit value: "end the membership", class:"btn btn-warning" %>
        <% end %>
        <% end %>
    <% end %>
        <br>
 <%= link_to 'Edit', edit_beer_club_path(@beer_club),class:"btn btn-info" %>
    <% if current_user.admin%>
 <%= link_to 'Destroy the club', @beer_club, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
<% end %>
<% end %>