config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs do
    post 'toggle_confirmed', on: :member
  end

  resources :users do
  post 'toggle_isfrozen', on: :member
  end

  resources :beers

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resource :session, only: [:new, :create, :destroy]

  root 'breweries#index'

  get 'kaikki_bisset', to: 'beers#index'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  get 'beerlist', to:'beers#list'

  get 'brewerylist', to:'breweries#list'

  get 'ngbeerlist', to:'beers#nglist'

  get 'auth/:provider/callback', to: 'sessions#create_oauth'

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

  resources :ratings, only: [:index, :new, :create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :ratings, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :beer_clubs, through: :memberships

  scope :is_frozen, -> { where isfrozen:true }
  scope :is_not_frozen, -> { where isfrozen:[nil,false] }

  validates :username, uniqueness: true
  validates :username, length: { minimum: 3 }
  validates :username, length: { maximum: 50 }

  PASSWORD_FORMAT = /\A
  (?=.*\d)           # Must contain a digit
  (?=.*[A-Z])        # Must contain an upper case character
/x

  validates :password, length: { minimum: 4 }
  validates :password, format: {with: PASSWORD_FORMAT, message: "must have at least 1 number and 1 big letter" }

  include RatingAverage

  has_secure_password

  def favorite_beer
    return nil if ratings.empty?
    ratings.order(score: :desc).limit(1).first.beer
  end

  def favorite_style
    favorite :style
  end

  def favorite_brewery
   favorite :brewery
  end

  def favorite(category)
   return nil if ratings.empty?

   rated = ratings.map{ |r| r.beer.send(category) }.uniq
   rated.sort_by { |item| -rating_of(category, item) }.first.name
  end

  def rating_of(category, item)
    ratings_of = ratings.select{ |r| r.beer.send(category)==item }
    ratings_of.map(&:score).inject(&:+) / ratings_of.count.to_f
  end


  def self.top(n)
    sorted_by_rating_in_desc_order = User.all.sort_by{ |b| -(b.ratings.size||0)}
    return sorted_by_rating_in_desc_order.first(n)
  end

  def beers_count
    lista = []
    if beers.size == 0
      return lista
    end
    luku = 0
    lista.push(beers.first)
    beers.each do |beer|
      lista.each do |beer1|
        if beer1 == beer
          luku = 1
        end
      end
      if luku == 0
        lista.push(beer)
      else
        luku = 0
      end
    end
    return lista
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:ratings, :beers).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
      respond_to do |format|
        if @user.update(user_params) and @user == current_user and @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if current_user == @user
      @user.destroy
      session[:user_id] = nil
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      return redirect_to :back
    end
  end

  def toggle_isfrozen
    user = User.find(params[:id])
    user.update_attribute :isfrozen, (not user.isfrozen)

    new_status = user.isfrozen? ? "is frosen" : "is not frozen"

    redirect_to :back, notice:"user account #{new_status}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <% if @user.new_record? %>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
    <% end %>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation  %>
    </div>
  <div class="actions">
    <%= f.submit class:'btn btn-success'%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password of <%= @user.username %></h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Username</th>
    <th> rated beers </th>
    <th> total ratings </th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers_count.size %></td>
        <td><%= user.ratings.size %></td>
        <td>
          <% if current_user%>
              <% if current_user.admin%>
                  <% if user.isfrozen%>
              <span class="label label-info">account frozen</span>
                  <% end %>
              <% end %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class:'btn btn-success' %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path, class:'btn btn-default'%>

app/views/users/show.html.erb
<p>
<h2><%= @user.username %>
  <% if current_user %>
      <% if current_user.admin %>
          <% if @user.isfrozen %>
              <span class="label label-info">account frozen</span>
          <% end %>
      <% end %>
  <% end %>
</h2>
</p>

<p>
<h3>Beer clubs</h3>

  <% if @user.beer_clubs.empty? %>
      user has not joined a club!
  <% else %>
      <strong>member of</strong>
        <ul>
      <% @user.beer_clubs.each do |club| %>
              <%if !club.hasApplied(@user) %>
          <li><%= link_to club.name, club %></li>
              <% end %>
      <% end %>
        </ul>
      <strong>applied membership of</strong>
    <ul>
      <% @user.beer_clubs.each do |club| %>
          <%if club.hasApplied(@user) %>
          <li><%= link_to club.name, beer_club_path(club) %></li>
            <% end %>
      <% end %>
      </ul>
  <% end %>
</p>

<p>
  <% if @user.favorite_style.nil? %>
       user has no favorite style!
  <% else %>
      favorite style <%= @user.favorite_style %>
  <% end %>
</p>

<p>
  <% if @user.favorite_brewery.nil? %>
      user has no favorite brewery!
  <% else %>
      favorite brewery <%= @user.favorite_brewery %>
  <% end %>
</p>

<p>
  <h3>ratings</h3>
<p>
  <% if @user.ratings.empty? %>
      user has not made ratings!
  <% else %>
      has made <%=pluralize(@user.ratings.count, 'rating') %>, average <%=@user.average_rating%>
  <% end %>
</p>
<ul>
  <% @user.ratings.each do |rating| %>
      <li>
        <%= rating %>
        <% if @user == current_user %>
            <%= link_to 'delete', rating_path(rating.id), method: :delete, data: { confirm: 'Are you sure?' }%>
        <% end %>
      </li>
  <% end %>
</ul>
</p>

<% if @user == current_user %>
<%= link_to 'Edit', edit_user_path(@user), class:"btn btn-info" %>
<%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
<% end %>
<% if current_user %>
    <% if current_user.admin %>
        <% if @user.isfrozen %>
    <%= link_to "reactivate account", toggle_isfrozen_user_path(@user.id), method: :post, class: "btn btn-danger" %>
        <% end %>
        <% if not @user.isfrozen %>
            <%= link_to "froze account", toggle_isfrozen_user_path(@user.id), method: :post, class: "btn btn-danger" %>
        <% end %>
    <% end %>
<% end %>
<%= link_to 'Back', users_path, class:"btn btn-default" %>